bwi_scavenger:
  scav_hunt_login:
    email: samiri1@binghamton.edu
    password: *****
  ws_path: /home/saeidfour/catkin_ws
  world: irl
  topics:
    perception:
      color: /camera/rgb/image_raw
      depth: /camera/depth/image
