darksocket_ros:
  topics:
    camera: /camera/rgb/image_color
    detections: /darksocket_ros/detections
  conf_path: /home/saeidfour/catkin_ws/src/scavenger_hunt_api/scavenger_hunt/src/darksocket/scripts/darksocket.conf
  telemetry: false
